import type { ElementType, EnergyCardDef, PokemonCardDef, Stage, TrainerCardDef } from '../game/types'
import type { CardPool, EvolutionLine } from './pokemonTcg'

// Offline safety net used only if the live Pokemon TCG API request fails
// (network unavailable, rate limited, etc). Stats are hand-picked so the
// game stays playable, with full official rules (60-card decks, all three
// evolution stages, Trainer cards), even without a network connection.
function mon(
  id: string,
  name: string,
  pokemonType: ElementType,
  stage: Stage,
  hp: number,
  attacks: PokemonCardDef['attacks'],
  retreatCost: number,
  weakness: ElementType | undefined,
  resistance: ElementType | undefined,
  evolvesFrom: string | undefined,
): PokemonCardDef {
  return {
    kind: 'pokemon',
    id,
    uid: '',
    name,
    pokemonType,
    stage,
    evolvesFrom,
    hp,
    attacks,
    retreatCost,
    weakness,
    resistance,
    imageSmall: `https://images.pokemontcg.io/base1/${id}.png`,
    imageLarge: `https://images.pokemontcg.io/base1/${id}_hires.png`,
  }
}

function atk(name: string, cost: ElementType[], damage: number, text = ''): PokemonCardDef['attacks'][number] {
  return { name, cost, damage, text, effects: [] }
}

const FALLBACK_LINES: EvolutionLine[] = [
  {
    basic: mon('46', 'Charmander', 'Fire', 'basic', 60, [atk('Ember', ['Fire'], 20)], 1, 'Water', undefined, undefined),
    stage1: mon(
      '24',
      'Charmeleon',
      'Fire',
      'stage1',
      90,
      [atk('Flamethrower', ['Fire', 'Colorless'], 50)],
      2,
      'Water',
      undefined,
      'Charmander',
    ),
    stage2: mon(
      '4',
      'Charizard',
      'Fire',
      'stage2',
      150,
      [atk('Fire Spin', ['Fire', 'Fire', 'Colorless', 'Colorless'], 100)],
      3,
      'Water',
      undefined,
      'Charmeleon',
    ),
  },
  {
    basic: mon('63', 'Squirtle', 'Water', 'basic', 60, [atk('Water Gun', ['Water'], 20)], 1, 'Lightning', undefined, undefined),
    stage1: mon(
      '42',
      'Wartortle',
      'Water',
      'stage1',
      90,
      [atk('Hydro Pump', ['Water', 'Colorless'], 40)],
      2,
      'Lightning',
      undefined,
      'Squirtle',
    ),
    stage2: mon(
      '2',
      'Blastoise',
      'Water',
      'stage2',
      150,
      [atk('Hydro Blast', ['Water', 'Water', 'Colorless', 'Colorless'], 100)],
      3,
      'Lightning',
      undefined,
      'Wartortle',
    ),
  },
  {
    basic: mon('44', 'Bulbasaur', 'Grass', 'basic', 60, [atk('Vine Whip', ['Grass'], 20)], 1, 'Fire', undefined, undefined),
    stage1: mon(
      '30',
      'Ivysaur',
      'Grass',
      'stage1',
      90,
      [atk('Razor Leaf', ['Grass', 'Colorless'], 40)],
      2,
      'Fire',
      undefined,
      'Bulbasaur',
    ),
    stage2: mon(
      '15',
      'Venusaur',
      'Grass',
      'stage2',
      150,
      [atk('Solar Beam', ['Grass', 'Grass', 'Colorless', 'Colorless'], 100)],
      3,
      'Fire',
      undefined,
      'Ivysaur',
    ),
  },
  {
    basic: mon('58', 'Pikachu', 'Lightning', 'basic', 60, [atk('Thunder Shock', ['Lightning'], 20)], 1, 'Fighting', undefined, undefined),
    stage1: mon(
      '14',
      'Raichu',
      'Lightning',
      'stage1',
      90,
      [atk('Thunderbolt', ['Lightning', 'Colorless'], 60, 'Flip a coin. If tails, this Pokémon does 10 damage to itself.')],
      1,
      'Fighting',
      undefined,
      'Pikachu',
    ),
  },
  {
    basic: mon('52', 'Machop', 'Fighting', 'basic', 70, [atk('Karate Chop', ['Fighting'], 20)], 1, 'Psychic', undefined, undefined),
    stage1: mon(
      '34',
      'Machoke',
      'Fighting',
      'stage1',
      100,
      [atk('Seismic Toss', ['Fighting', 'Colorless'], 50)],
      3,
      'Psychic',
      undefined,
      'Machop',
    ),
    stage2: mon(
      '8',
      'Machamp',
      'Fighting',
      'stage2',
      170,
      [atk('Submission', ['Fighting', 'Fighting', 'Colorless'], 90, 'This attack also does 20 damage to itself.')],
      4,
      'Psychic',
      undefined,
      'Machoke',
    ),
  },
  {
    basic: mon('43', 'Abra', 'Psychic', 'basic', 50, [atk('Confuse Ray', ['Psychic'], 10)], 1, undefined, undefined, undefined),
    stage1: mon(
      '32',
      'Kadabra',
      'Psychic',
      'stage1',
      80,
      [atk('Psybeam', ['Psychic', 'Colorless'], 40)],
      2,
      undefined,
      undefined,
      'Abra',
    ),
    stage2: mon(
      '1',
      'Alakazam',
      'Psychic',
      'stage2',
      130,
      [atk('Psychic', ['Psychic', 'Colorless', 'Colorless'], 80)],
      3,
      undefined,
      undefined,
      'Kadabra',
    ),
  },
  {
    basic: mon('27', 'Sandshrew', 'Fighting', 'basic', 60, [atk('Sand-attack', ['Fighting'], 10)], 1, 'Grass', undefined, undefined),
    stage1: mon(
      '28',
      'Sandslash',
      'Fighting',
      'stage1',
      90,
      [atk('Slash', ['Fighting', 'Colorless'], 40)],
      2,
      'Grass',
      undefined,
      'Sandshrew',
    ),
  },
  {
    basic: mon('37', 'Vulpix', 'Fire', 'basic', 50, [atk('Confuse Ray', ['Fire'], 20, 'The Defending Pokémon is now Confused.')], 1, 'Water', undefined, undefined),
    stage1: mon(
      '17',
      'Ninetales',
      'Fire',
      'stage1',
      90,
      [atk('Fire Blast', ['Fire', 'Fire', 'Colorless'], 60)],
      1,
      'Water',
      undefined,
      'Vulpix',
    ),
  },
  {
    basic: mon('67', 'Koffing', 'Darkness', 'basic', 50, [atk('Poison Gas', ['Darkness'], 10, 'The Defending Pokémon is now Poisoned.')], 1, 'Psychic', undefined, undefined),
    stage1: mon(
      '13',
      'Weezing',
      'Darkness',
      'stage1',
      80,
      [atk('Smog', ['Darkness', 'Colorless'], 30, 'Flip a coin. If heads, the Defending Pokémon is now Poisoned.')],
      2,
      'Psychic',
      undefined,
      'Koffing',
    ),
  },
  {
    basic: mon('81', 'Magnemite', 'Metal', 'basic', 50, [atk('Thunder Wave', ['Metal'], 10, 'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.')], 1, 'Fighting', undefined, undefined),
    stage1: mon(
      '9',
      'Magneton',
      'Metal',
      'stage1',
      90,
      [atk('Selfdestruct', ['Metal', 'Colorless', 'Colorless'], 80, 'This attack also does 80 damage to itself.')],
      1,
      'Fighting',
      undefined,
      'Magnemite',
    ),
  },
  {
    basic: mon('35', 'Clefairy', 'Fairy', 'basic', 60, [atk('Sing', ['Fairy'], 0, 'The Defending Pokémon is now Asleep.')], 1, undefined, undefined, undefined),
  },
  {
    basic: mon('51', 'Eevee', 'Colorless', 'basic', 60, [atk('Tackle', ['Colorless'], 20)], 1, undefined, undefined, undefined),
  },
]

const FALLBACK_TRAINERS: TrainerCardDef[] = [
  {
    kind: 'trainer',
    id: 'base1-71',
    uid: '',
    name: 'Potion',
    trainerType: 'item',
    text: 'Heal 20 damage from 1 of your Pokémon.',
    effects: [{ kind: 'heal', amount: 20 }],
    imageSmall: 'https://images.pokemontcg.io/base1/71.png',
    imageLarge: 'https://images.pokemontcg.io/base1/71_hires.png',
  },
  {
    kind: 'trainer',
    id: 'base1-95',
    uid: '',
    name: 'Switch',
    trainerType: 'item',
    text: 'Switch your Active Pokémon with 1 of your Benched Pokémon.',
    effects: [{ kind: 'switchSelfActive' }],
    imageSmall: 'https://images.pokemontcg.io/base1/95.png',
    imageLarge: 'https://images.pokemontcg.io/base1/95_hires.png',
  },
  {
    kind: 'trainer',
    id: 'base1-73',
    uid: '',
    name: 'Energy Search',
    trainerType: 'item',
    text: 'Search your deck for a basic Energy card and put it into your hand. Shuffle your deck afterward.',
    effects: [{ kind: 'searchDeckForEnergy', amount: 1 }],
    imageSmall: 'https://images.pokemontcg.io/base1/73.png',
    imageLarge: 'https://images.pokemontcg.io/base1/73_hires.png',
  },
  {
    kind: 'trainer',
    id: 'base1-88',
    uid: '',
    name: 'Professor Oak',
    trainerType: 'supporter',
    text: 'Discard your hand, then draw 7 cards.',
    effects: [{ kind: 'handRefresh', shuffleBack: false, amount: 7 }],
    imageSmall: 'https://images.pokemontcg.io/base1/88.png',
    imageLarge: 'https://images.pokemontcg.io/base1/88_hires.png',
  },
]

function energy(id: string, type: ElementType): EnergyCardDef {
  return {
    kind: 'energy',
    id,
    uid: '',
    name: `${type} Energy`,
    energyType: type,
    imageSmall: `https://images.pokemontcg.io/base1/${id}.png`,
    imageLarge: `https://images.pokemontcg.io/base1/${id}_hires.png`,
  }
}

const FALLBACK_ENERGY: Record<ElementType, EnergyCardDef | undefined> = {
  Fire: energy('98', 'Fire'),
  Water: energy('102', 'Water'),
  Grass: energy('99', 'Grass'),
  Lightning: energy('100', 'Lightning'),
  Fighting: energy('97', 'Fighting'),
  Psychic: energy('101', 'Psychic'),
  Darkness: energy('base2-4', 'Darkness'),
  Metal: energy('neo1-98', 'Metal'),
  Fairy: energy('xy1-95', 'Fairy'),
  Dragon: undefined,
  Colorless: undefined,
}

export const FALLBACK_POOL: CardPool = {
  lines: FALLBACK_LINES,
  trainers: FALLBACK_TRAINERS,
  energy: FALLBACK_ENERGY,
}
