import type { ElementType, EnergyCardDef, PokemonCardDef } from '../game/types'

// Offline safety net used only if the live Pokemon TCG API request fails
// (network unavailable, rate limited, etc). Stats are hand-picked so the
// game stays playable even without a network connection.
function mon(
  id: string,
  name: string,
  pokemonType: ElementType,
  stage: 'basic' | 'stage1',
  hp: number,
  attacks: PokemonCardDef['attacks'],
  retreatCost: number,
  weakness: ElementType | undefined,
  evolvesFrom: string | undefined,
): PokemonCardDef {
  return {
    kind: 'pokemon',
    id,
    uid: '',
    name,
    pokemonType,
    stage,
    evolvesFrom,
    hp,
    attacks,
    retreatCost,
    weakness,
    imageSmall: `https://images.pokemontcg.io/base1/${id}.png`,
    imageLarge: `https://images.pokemontcg.io/base1/${id}_hires.png`,
  }
}

export const FALLBACK_POKEMON: Record<string, PokemonCardDef> = {
  Charmander: mon(
    '46',
    'Charmander',
    'Fire',
    'basic',
    60,
    [{ name: 'Ember', cost: ['Fire'], damage: 20, text: '' }],
    1,
    'Water',
    undefined,
  ),
  Charmeleon: mon(
    '24',
    'Charmeleon',
    'Fire',
    'stage1',
    90,
    [{ name: 'Flamethrower', cost: ['Fire', 'Colorless'], damage: 50, text: '' }],
    2,
    'Water',
    'Charmander',
  ),
  Squirtle: mon(
    '63',
    'Squirtle',
    'Water',
    'basic',
    60,
    [{ name: 'Water Gun', cost: ['Water'], damage: 20, text: '' }],
    1,
    'Lightning',
    undefined,
  ),
  Wartortle: mon(
    '42',
    'Wartortle',
    'Water',
    'stage1',
    90,
    [{ name: 'Hydro Pump', cost: ['Water', 'Colorless'], damage: 40, text: '' }],
    2,
    'Lightning',
    'Squirtle',
  ),
  Bulbasaur: mon(
    '44',
    'Bulbasaur',
    'Grass',
    'basic',
    60,
    [{ name: 'Vine Whip', cost: ['Grass'], damage: 20, text: '' }],
    1,
    'Fire',
    undefined,
  ),
  Ivysaur: mon(
    '30',
    'Ivysaur',
    'Grass',
    'stage1',
    90,
    [{ name: 'Razor Leaf', cost: ['Grass', 'Colorless'], damage: 40, text: '' }],
    2,
    'Fire',
    'Bulbasaur',
  ),
  Pikachu: mon(
    '58',
    'Pikachu',
    'Lightning',
    'basic',
    60,
    [{ name: 'Thunder Shock', cost: ['Lightning'], damage: 20, text: '' }],
    1,
    'Fighting',
    undefined,
  ),
  Raichu: mon(
    '14',
    'Raichu',
    'Lightning',
    'stage1',
    90,
    [{ name: 'Thunderbolt', cost: ['Lightning', 'Colorless'], damage: 50, text: '' }],
    2,
    'Fighting',
    'Pikachu',
  ),
  Machop: mon(
    '52',
    'Machop',
    'Fighting',
    'basic',
    70,
    [{ name: 'Karate Chop', cost: ['Fighting'], damage: 20, text: '' }],
    1,
    'Psychic',
    undefined,
  ),
  Machoke: mon(
    '34',
    'Machoke',
    'Fighting',
    'stage1',
    100,
    [{ name: 'Seismic Toss', cost: ['Fighting', 'Colorless'], damage: 50, text: '' }],
    3,
    'Psychic',
    'Machop',
  ),
  Abra: mon(
    '43',
    'Abra',
    'Psychic',
    'basic',
    50,
    [{ name: 'Confuse Ray', cost: ['Psychic'], damage: 10, text: '' }],
    1,
    undefined,
    undefined,
  ),
  Kadabra: mon(
    '32',
    'Kadabra',
    'Psychic',
    'stage1',
    80,
    [{ name: 'Psybeam', cost: ['Psychic', 'Colorless'], damage: 40, text: '' }],
    2,
    undefined,
    'Abra',
  ),
  Eevee: mon(
    '51',
    'Eevee',
    'Colorless',
    'basic',
    60,
    [{ name: 'Tackle', cost: ['Colorless'], damage: 20, text: '' }],
    1,
    undefined,
    undefined,
  ),
}

function energy(id: string, type: ElementType): EnergyCardDef {
  return {
    kind: 'energy',
    id,
    uid: '',
    name: `${type} Energy`,
    energyType: type,
    imageSmall: `https://images.pokemontcg.io/base1/${id}.png`,
    imageLarge: `https://images.pokemontcg.io/base1/${id}_hires.png`,
  }
}

export const FALLBACK_ENERGY: Record<ElementType, EnergyCardDef> = {
  Fire: energy('98', 'Fire'),
  Water: energy('102', 'Water'),
  Grass: energy('99', 'Grass'),
  Lightning: energy('100', 'Lightning'),
  Fighting: energy('97', 'Fighting'),
  Psychic: energy('101', 'Psychic'),
  Colorless: energy('101', 'Colorless'),
}
